spring.application.name=StudentCourseManagement

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/student_management}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:sakeeb}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:U3R1ZGVudENvdXJzZU1hbmFnZW1lbnRTZWNyZXRLZXlGb3JQcm9qZWN0MjAyNg==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:600000}
